### ISSUE TITLE
Parser errors tend to break out of container

### ISSUE THREAD

**Issue by conradj** [gareththegeek/corewar-ui#103]
See issues https://github.com/gareththegeek/corewar/issues/119, https://github.com/gareththegeek/corewar/issues/118,
https://github.com/gareththegeek/corewar/issues/117

for some Warriors that create parser errors. They tend to break out of the container and do funny things to the UI.

**Comment by dougajmcdonald** [comment]
Will be resolved in UI v2

**Comment by dougajmcdonald** [comment]
Now fixed on staging site
