### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by dougajmcdonald** [gareththegeek/corewar-ui#13]
Once we have automated UI tests, add CI via wercker for this project too

**Comment by gareththegeek** [comment]
I have protected the master branch from failing wercker build - now we just need to get the build to pass!

**Comment by dougajmcdonald** [comment]
So I downloaded docker and tried to package the app, when I run it I get the same type of errors so I'm going to assume it's a reference issue isolated to containers I'll play about tonight to see if I can work out why

**Comment by dougajmcdonald** [comment]
Closing as this is now sorted #15
