### ISSUE TITLE
App hangs when clicking Finish Button

### ISSUE THREAD

**Issue by gareththegeek** [gareththegeek/corewar-ui#134]
1. Enter an imp (mov 0, 1)
2. Click Add
3. Click Finish (chequered flag)

The app hangs giving a browser long running script error
Seems ok if you click init before clicking finish

**Comment by dougajmcdonald** [comment]
![everything-is-fine-meme-59d316b6d0c13](https://user-images.githubusercontent.com/1190042/34720707-93c68992-f537-11e7-9a6a-457a94fe3c20.jpg)

**Comment by dougajmcdonald** [comment]
Resolved and deployed
