### ISSUE TITLE
Cannot add warrior to core if parser warnings are present

### ISSUE THREAD

**Issue by gareththegeek** [gareththegeek/corewar-ui#144]
If I parse a warrior and receive a parser warning (but no errors), I should be able to add the warrior to core but I can't.  Clicking the Add button does nothing.

The following redcode generates a warning but no errors for example:

```
label1 mov 0, 1
label1 mov 0, 1
```

**Comment by dougajmcdonald** [comment]
Ah ok, I was assuming any parser messages meant not being able to add it. Can relax this if you want your shoddy warriors in the core!

**Comment by dougajmcdonald** [comment]
You can now add with warnings and info, just not errors:

#159
