### ISSUE TITLE
Next execution address should be highlighted

### ISSUE THREAD

**Issue by gareththegeek** [gareththegeek/corewar-ui#179]
The next address to be executed should be highlighted white.  Past implementations were highlighting the previously executed address but this is incorrect.  Imaging the situation when you are debugging code in an IDE.  The debugger will highlight the line of code which is **about** to be executed, not the line of code that has just been executed.

Currently I don't think this is possible to implement as the next execution address is not provided from the  core library so we will probably need to introduce a new message to cater for this....

**Comment by gareththegeek** [comment]
A `NEXT_EXECUTION` message is published by the core library each step to indicate the next address to be executed and the executing warrior id (and data).  We should be able to use this information to highlight the correct cell.

**Comment by gareththegeek** [comment]
Should be resolved by #248

**Comment by dougajmcdonald** [comment]
Agreed, resolved
