### ISSUE TITLE
Large core sizes don't render so well

### ISSUE THREAD

**Issue by dougajmcdonald** [gareththegeek/corewar-ui#207]
I tried to pop in a 90,000 core size and it didn't work so good!

![image](https://user-images.githubusercontent.com/1190042/36493702-1eeb23f4-1728-11e8-8416-1c78ee7d1a64.png)

**Comment by gareththegeek** [comment]
I expect current logic is this:

What size tiles will fit?
- 1x1 pixel fits and 2x2 pixel doesn't

So how many 1 pixel cells fit in a row
  - loads

Ok we end up with a very few rows with tons of 1 pixel cells in them

**Comment by gareththegeek** [comment]
I'm not sure what else can be done unless we go sub pixel or make the area scrollable.
I guess we could tweak rendering so that it tries to make the core more square, but it will still just be a tiny grey square instead of a tiny grey rectangle!

**Comment by dougajmcdonald** [comment]
I wonder if I need to implement a fullscreen mode. It would be quite tricky I think to ensure it works nicely cross device, but perhaps on mobile / tablet we don't need it as the simulator is basically full screen on those anyway, thoughts?

**Comment by dougajmcdonald** [comment]
Possibly resolved by #221

**Comment by dougajmcdonald** [comment]
Closing as we can't do a lot about this. Slightly better now we have more core to play with since moving to file browser concept
