### ISSUE TITLE
Core colours don't match file colours

### ISSUE THREAD

**Issue by dougajmcdonald** [gareththegeek/corewar-ui#230]
If we have a list of warriors and I toggle one of them off, I filter the warriors which get passed to the core so passing 2 warriors to core, but there may be 3 files.

The colours I'm using for the icons are based on 3 warriors, but the core assumes the colours based on the warrior index and in the example here will only have two warriors. 
As a result it's possible to have colours in the core which don't match the files:

In the below example the colour indexes are blue[0], red[1], yellow[2] which is what the tabs along the top show. But in the core the vampire is toggled off which results in the blur scanner being coloured red when it should be yellow.
The file list shouldn't change but the core colours should use the file indexes not the warrior indexes to determine their colours:

![image](https://user-images.githubusercontent.com/1190042/37555245-609aad26-29dc-11e8-860a-2088b2f20de2.png)

**Comment by dougajmcdonald** [comment]
One way to fix this might be to rework how the colours are assigned, using a `colour` property on the warrior rather than index perhaps (determined when the warrior is added in the UI) I think would need the `colour` property to be added to the `CORE_ACCESS` event.
I think this would add UI concerns to the core project which doesn't seem ideal.

A better way might be to re-introduce a guid for each warrior and use that instead of the warrior id (on both UI and core) I can create a colour map on the UI and tweak the simulator canvas to look that up when rendering sprites, rather than using array index. This again would require core changes though.

Any thoughts @gareththegeek ?

**Comment by gareththegeek** [comment]
Should be possible once https://github.com/gareththegeek/corewar/issues/168 is completed
