### ISSUE TITLE
Removing all warriors causes crash

### ISSUE THREAD

**Issue by dougajmcdonald** [gareththegeek/corewar-ui#257]
The current project of removing warriors re-inits each time.

It's now possible to remove them all which crashes the core if innited with zero warriors

**Comment by dougajmcdonald** [comment]
@gareththegeek  Should I be preventing a re-init with zero warriors? or should the core handle it?

**Comment by gareththegeek** [comment]
I'll update the core library - raised https://github.com/gareththegeek/corewar/issues/179
