### ISSUE TITLE
Expired SSL cert.

### ISSUE THREAD

**Issue by jakubmikusek** [gareththegeek/corewar-ui#309]
Hi Gareth,

The certificate for https://www.corewar.io/ has expired on 30th Oct 2018.
Also the /contact-us/ is 404.

**Comment by dougajmcdonald** [comment]
@jakubmikusek thanks for the heads up. I will renew thew cert, it should have auto renewed but that's obviously not worked as expected! 

We have seen some odd 404 errors over time which seem related the SSL cert I believe. Oddly the page without the `www` works ok: https://corewar.io/contact-us

**Comment by dougajmcdonald** [comment]
I've updated the cert and hopefully fixed any issues with the auto renew by updating the extension within Azure. 

Let me know if you hit any further snags
