### ISSUE TITLE
Allow warriors to be toggled on or off 

### ISSUE THREAD

**Issue by dougajmcdonald** [gareththegeek/corewar-ui#33]
To make it easier to select from a pool of warriors

**Comment by dougajmcdonald** [comment]
At the moment they can be added and removed, is that enough? if we make it easy to add and remove?

**Comment by gareththegeek** [comment]
I suppose the problem is that currently you have to enter the source code again to get them back

**Comment by dougajmcdonald** [comment]
I'm imagining the add button persists the warrior to you account maybe? Then you can select from a drop-down or similar to get it back?
Main issue with that is versioning / uniquely naming

**Comment by gareththegeek** [comment]
I think this issue can be closed but there is a residual issue around being able to load/save warriors and possibly retrieve any warriors which you have deployed during your session, or possibly a list of recently accessed warriors...
