### ISSUE TITLE
Add ui tests

### ISSUE THREAD

**Issue by dougajmcdonald** [gareththegeek/corewar-ui#4]
We should ensure UI tests are added to this project so it's tested AF like the other project!

**Comment by dougajmcdonald** [comment]
I've begun working on these but don't want to go to the Nth degree till I understand things better and we have a firmer vision of the UI endgame #15

**Comment by gareththegeek** [comment]
That sounds sensible!

**Comment by dougajmcdonald** [comment]
more added in #52

**Comment by dougajmcdonald** [comment]
and #102
